### ISSUE TITLE
Srcery Slack theme

### ISSUE THREAD

**Issue by c9rgreen** [srcery-colors/srcery-misc#1]
`#1c1b19,#2D2C29,#444444,#FCE8C3,#2D2C29,#FCE8C3,#519F50,#2C78BF`

Here's a Srcery Slack theme that I'm using. I'm not sure which repo to file a pull request against.

**Comment by roosta** [comment]
Hi, thank you for the contribution! [srcery-gui](https://github.com/srcery-colors/srcery-gui) would be the best place for it I think, do you want to add a pull request or should I add it?

**Comment by c9rgreen** [comment]
I went ahead and created a pull request: https://github.com/srcery-colors/srcery-gui/pull/3
